trigger:
  branches:
    include:
      - main

variables:
  VM_IP_PUBLICA: '20.110.76.231'  # Se debe colocar la IP pública de tu máquina virtual
  IMAGE_NAME: 'mybdmysql'
  ACR_NAME: 'acrdevops002agrupo03'
  ACR_USERNAME: 'acrdevops002agrupo03'
  ACR_PASSWORD: '9QMRoidxj3Urx8M3At5NfEWhEI8ztzniVNqkPM31WLkaXZo3NHqTJQQJ99CJACHYHv6Eqg7NAAACAZCRpPyH'

stages:
  - stage: Deploy
    jobs:
      - deployment: DeployToVM
        displayName: 'Deploy MySQL to VM'
        environment:
          name: 'VMDockerS3'
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
                      echo "Esperando que apt termine otra tarea..."
                      sleep 5
                    done

                    if ! command -v az &> /dev/null; then
                      echo "Azure CLI no esta instalado. Instalando Azure CLI..."
                      export DEBIAN_FRONTEND=noninteractive
                      sudo apt-get update && \
                      sudo apt-get install -y curl && \
                      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && \
                      az --version
                    else
                      echo "Azure CLI ya esta instalado."
                    fi
                  displayName: 'Verificar e Instalar Azure CLI'

                - script: |
                    while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
                      echo "Esperando que apt termine otra tarea..."
                      sleep 5
                    done

                    if ! command -v docker &> /dev/null; then
                      echo "Docker no esta instalado. Instalando Docker..."
                      export DEBIAN_FRONTEND=noninteractive
                      sudo apt-get update && \
                      sudo apt-get install -y \
                        apt-transport-https \
                        ca-certificates \
                        curl \
                        gnupg \
                        lsb-release && \
                      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg && \
                      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
                      sudo apt-get update && \
                      sudo apt-get install -y docker-ce docker-ce-cli containerd.io && \
                      sudo systemctl start docker && \
                      sudo systemctl enable docker && \
                      sudo docker --version
                    else
                      echo "Docker ya esta instalado."
                    fi
                  displayName: 'Verificar e Instalar Docker'

                - script: |
                    set -e
                    echo "Autenticandose en Azure Container Registry..."
                    echo "${ACR_PASSWORD}" | sudo docker login ${ACR_NAME}.azurecr.io -u ${ACR_USERNAME} --password-stdin

                    echo "Descargando la imagen desde ACR..."
                    sudo docker pull ${ACR_NAME}.azurecr.io/${ACR_NAME}.azurecr.io/${IMAGE_NAME}:latest

                    echo "Eliminando contenedor anterior (si existe)..."
                    sudo docker rm -f mysql_container || true

                    echo "Creando y ejecutando mysql_container..."
                    sudo docker run -d -p 3306:3306 --name mysql_container \
                      -e MYSQL_ROOT_PASSWORD=Password123 \
                      -e MYSQL_DATABASE=my_database \
                      -e MYSQL_USER=mysqluser \
                      -e MYSQL_PASSWORD=Password123 \
                      ${ACR_NAME}.azurecr.io/${ACR_NAME}.azurecr.io/${IMAGE_NAME}:latest

                    sleep 5
                    sudo docker ps
                  displayName: 'Descargar y ejecutar la imagen MySQL desde ACR'

                - script: |
                    echo "Conectar a MySQL en la maquina virtual con la IP: ${VM_IP_PUBLICA}, puerto: 3306"
                  displayName: 'Mostrar detalles de conexion a MySQL'
